apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-device-data
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-device
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: iot-device-data
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: iot-device-data
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: iot-device-data
          patternType: literal
        operation: Describe
        host: "*"
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: camel-kafka-influxdb
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: iot-device-data
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: iot-device-data
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: camel-group
          patternType: literal
        operation: Read
        host: "*"